name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "[BUG] <description>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      id: description_bug
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      id: screenshots_bug
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional information?
      id: info_bug
      description: Any additional information or Is there anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    id: browsers_bug
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Opera
        - Other
  - type: checkboxes
    id: checklist_bug
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
