name: Feature Request 💡
description: Have any new idea or new feature? Please suggest!
title: "[Feature] <description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description_feature
    attributes:
      label: Description
      description: A clear and concise description of any alternative solution or features you've considered.
    validations:
      required: true
  - type: textarea
    id: screenshots_feature
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: checkboxes
    id: checklist_feature
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
