name: Script Addition 💻
description: Have any new script you wish to add? Please use this!
title: "[Feat] <description>"
labels: ["goal: script-addition"]
body:
  - type: input
    id: aim_script
    attributes:
      label: "AIM"
      description: "A clear and concise description of the aim of your script."
    validations:
      required: true
  - type: textarea
    id: feature_script
    attributes:
      label: "Features"
      description: "Describe all the features of your script"
    validations:
      required: true
  - type: checkboxes
    id: checklist_feature
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/blob/master/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
