name: Auto Comment on Pull Request
on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = "Thank you for creating the pull request! We will review it shortly.";

            // Use github object directly, it should have the createComment method
            github.issues.createComment({
              issue_number: context.payload.pull_request.number, // Changed pull_number to issue_number
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
